### PR TITLE
Fix iframe embed support

### LINKED ISSUE #3772: Embedding rooms in an iframe has stopped working
Since the update (25 Jan 2021) it appears that you can no longer embedded a Hubs room in an iframe. On Chrome 88 on MacOS I get the following console log error:

console.js:35 TypeError: Cannot read property 'canOrWillIfCreator' of undefined
    at Dv.render (ui-root.js:1082)
    at Lo (react-dom.production.min.js:182)
    at Io (react-dom.production.min.js:181)
    at gu (react-dom.production.min.js:263)
    at cl (react-dom.production.min.js:246)
    at ul (react-dom.production.min.js:246)
    at Ju (react-dom.production.min.js:239)
    at Qu (react-dom.production.min.js:230)
    at Rl (react-dom.production.min.js:281)
    at react-dom.production.min.js:284
    at tl (react-dom.production.min.js:240)
    at Hl (react-dom.production.min.js:284)
    at Object.t.render (react-dom.production.min.js:290)
    at hub.js:294
    at dO (hub.js:327)
    at HTMLDocument.<anonymous> (hub.js:837)
    at Generator.next (<anonymous>)
    at GC (hub-c5528134c464e17d3a9e.js:1)
    at o (hub-c5528134c464e17d3a9e.js:1)

Embedding continues to work find for my own Hubs Cloud, which is obviously on an older version of the code.

### PR DESCRIPTION
**Pull request by brianpeiris**
Mainly needed to add some null reference checks, since when we embed in an iframe, we display an initial loading screen without any information about a hub or hubChannel.
Also fixed a few instances where we generate room URLs to make them work in local dev environments.

Fixes #3772

### CODE REVIEW

File: src/utils/phoenix-utils.js [hunk 1]
```diff
@@ -12,15 +12,30 @@ export function isLocalClient() {
   return hasReticulumServer() && document.location.host !== configs.RETICULUM_SERVER;
 }
 
-export function hubUrl(hubId) {
+export function hubUrl(hubId, extraParams) {
```
Comment (robertlong) [inline src/utils/phoenix-utils.js:15]: This is a great addition :+1:

**Review by robertlong — APPROVED** [review]
Looks great!
