### PR TITLE
Fix 3D models Media Frame scaling issues and add support for 3D preview

### LINKED ISSUE #4089: Media zones will sometimes make the object inserted enormous
**Description**
When adding an object to a media zone, the action results in the following:
- All nearby media zones are occupied as well (greyed out, no actual object inside)
- Removing the object from the original media zone will scale it so it covers the entire world and is impossible to delete

**To Reproduce**
Put a bunch of media zones together
Place object

Happens very inconsistently so its hard to reproduce, but i have gotten the bug to consistently happen when using 3d objects that have less than 1,1,1 scale, most likely the algorithm calculating new object size will go nuts. It also happens using images, often with our custom "post it note" feature but also other images.

**Expected behavior**
The object should not occupy other nearby media zones, and should pop out to its normal scale upon removal.

**Hardware** 
 - Device: Desktop
 - OS: MacOS, Windows, Linux
 - Browser: Chrome, FF

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #4089

This PR fixes a couple of issues with media frames and 3D object:
- Fixes the scale issues when the object is captured
- Adds full support for 3D object preview

### CODE REVIEW

File: src/systems/media-frames.js [hunk 1]
```diff
@@ -262,22 +332,38 @@ AFRAME.registerComponent("media-frame", {
...
-      capturableEntity.components["floaty-object"].setLocked(true);
+      const update = () => {
+        this.el.setAttribute("media-frame", {
+          targetId: capturableEntity.id,
+          originalTargetScale: new THREE.Vector3().copy(capturableEntity.object3D.scale)
+        });
+
+        capturableEntity.object3D.scale.set(1, 1, 1);
+        capturableEntity.object3D.quaternion.set(0, 0, 0, 1);
+        capturableEntity.object3D.updateMatrixWorld();
```
Comment (netpro2k) [inline src/systems/media-frames.js:343]: Don't think this is needed but you should set `matrixNeedsUpdate` since scale/quaternion was just changed.

**Review by netpro2k — COMMENTED** [review]
lgtm. Thanks for getting this fixed up! If I had implemented this I would have been too lazy to support animated previews, but that's a nice touch :) - Made a few comments, mostly around the matrix world update contract. I think most of my comments are noop changes so no strong opinions on if you bother changing them if you have already done a bunch of testing.
