### PR TITLE
Bunch of HLS fixes

### LINKED ISSUE #2572: HLS stream FxR hack makes buffering unpredictable
**Description**
While using HLS m3u8 streams (with and without adaptive bitrate indexes) users may experience stuttering / choppy video stream. My best guess is that the video player is not able to buffer properly and is forced to stay on edge of video stream (making buffering unused) because of the FxR hack in media-views.js:697

`this.video.currentTime = this.video.duration - 0.01`

Setting the value to for example 4 instead of 0.01 makes the video transitions between HLS adaptive streams much smoother as well as overall HLS performance better because I guess the player is able get some buffer time.

**To Reproduce**
1. Set a m3u8 source for a video element in Spoke
2. Some users experience stuttering
3. Change value from 0.01 to some number (depends on your parameters for HLS stream and how many fragments etc. you are buffering, setting it too high (essentially setting the video time back further than the video itself) will actually refresh the whole website from my experience)
4. Get smoother HLS

**Expected behavior**
HLS Streams in a-frame should buffer and be predictable like a normal video element.

**Hardware** 
Tested on various users on Mac OS, Windows, Linux, performance reported as better. No extensive / structured testing performed. Might need to verify root cause. We are not using VR gear.

**Additional context**

Also talked to @netpro2k about this in Discord on May 10th, in #dev-general. (Just search for "adaptive HLS seems much smoother now compared" in #dev-general discord channel to find the conversation.)

### PR DESCRIPTION
**Pull request by netpro2k**
A round of fixes for HLS videos. A lot of this is just removing hacks we have in place and letting HLS.js do its thing. I have still run into cases where I can get the player to stall indefinitely, but adding a manual refresh button should hopefully alleviate most of these. Probably not the last round of these but seems worth cutting a PR for.

- Update HLS.js to 0.14.6 (from 0.13.2), contains a whole bunch of bugfixes which people may or may not be hitting. Given the complexity of HLS and wide userbase of HLS.js it seems worth keeping this as up to date as we can.
- Fix handling of audio-only streams (fixes #2521)
- The XHR override we were using was running in sync mode, this was likely slowing requests down and stalling the main thread. Fixed to be async as is the default in HLS.js
- Enable refresh buttons in the pause menu for all objects. We were previously limiting this just to live twitch streams, but it feels generally useful and is a better option than page refresh. When the media is an HLS stream, uses `recoverMediaError()` in hls.js instead of a hard resolve-level refresh.
- Not in this PR but linking here since its related to this round of fixes, and should enable the client to actually do adaptive bitrate streaming when available in the source playlist https://github.com/mozilla/reticulum/pull/397
- Remove HLS timeout hacks. HLS.js has a bunch of internal logic for this already and we are just messing with it. In cases HLS.js stalls out (still can make it happen) the manual refresh above seems preferable and less likely to break what would have otherwise been a working stream. This is especially important with the fixes to adaptive bitrate streaming, since it should automatically fallback to lower bitrate streams if things are taking too long to load.
- Remove hacks we had in place for seeking ahead on live videos. This is handled internally already in HLS.js and us doing it messes with the buffering (fixes #2572)
- added `hlsDebug` query param to turn on HLS.js debugging to help diagnose future issues

### CODE REVIEW

File: src/components/media-loader.js [hunk 1]
```diff
@@ -402,7 +402,7 @@ AFRAME.registerComponent("media-loader", {
       }
 
       // Some servers treat m3u8 playlists as "audio/x-mpegurl", we always want to treat them as HLS videos
-      if (contentType === "audio/x-mpegurl") {
+      if (contentType === "audio/x-mpegurl" || contentType === "audio/mpegurl") {
```
Comment (johnshaughnessy) [inline src/components/media-loader.js:405]: Not sure, but we might want to check `"application/x-mpegurl"`, `"application/mpegurl"`, and `"application/vnd.apple.mpegurl.audio"` as per https://en.wikipedia.org/wiki/M3U#Internet_media_types

File: src/components/refresh-media-button.js [hunk 2]
```diff
@@ -4,36 +4,23 @@ AFRAME.registerComponent("local-refresh-media-button", {
...
     this.onClick = async () => {
       if (this.targetEl) {
-        this.targetEl.components["media-loader"] &&
-          this.targetEl.components["media-loader"].update(this.targetEl.components["media-loader"].data, true);
+        const c = this.targetEl.components;
+        // If an HLS stream is loaded, refresh directly with HLS.js
+        if (c["media-video"] && c["media-video"].videoTexture && c["media-video"].videoTexture.hls) {
+          c["media-video"].videoTexture.hls.recoverMediaError();
+        } else if (c["media-loader"]) {
+          // Otherwise fall back to hard resolve-level refresh which should work for any meida
```
Comment (johnshaughnessy) [inline src/components/refresh-media-button.js:12]: typo "...  which should work for any ~meida~ media"

**Comment by camelgod** [comment]
FYI Related issue could be referenced:
https://github.com/mozilla/hubs/issues/2104
