### PR TITLE
Resolve the audio noise problem happened at the moment when zooming in an object

### LINKED ISSUE #3098: Sometimes audio noise can happen at the moment when zooming in an object
**Description**

Sometimes, not always, audio noise can happen at the moment when zooming in an object if someone in the room is speaking.

**To Reproduce**

* Enter a room
* Run a bot with audio `node run-bot.js -a bot-recording.mp3 -r roomId`
* Place an asset like a picture anywhere in the room
* Press f on the asset and zoom in
* Confirm that an audio noise can happen. If it doesn't, repeatedly press until it happens

If the audio noise doesn't happen, move close to or far from the bot and try again. It seems this problem very depends on the distance from the speaker or audio volume.

**Expected behavior**

Audio noise doesn't happen.

**Hardware** 
 - Device: [e.g. Desktop, phone, VR headset] Desktop
 - OS: [e.g. Windows, iOS, Linux] Windows
 - Browser [e.g. Firefox] Firefox and Chrome

**Additional context**

* In my environment, it happens both on Firefox and Chrome but I feel it happens more easily on Chrome? No confidence tho.
* As I wrote in "To reproduce", this problem seems very depending on the distance from the speaker or audio volume. In my test, it may happen more easily if I am closer to the bot?
* It doesn't seem to happen at the moment when you are back to normal from zoom in mode.

### PR DESCRIPTION
**Pull request by takahirox**
Resolves #3098

**How the audio noise problem happens**

@johnshaughnessy's https://github.com/mozilla/hubs/issues/3098#issuecomment-703917282 seems correct.

1. Audio listener's parent is viewing camera in non-inspect mode
2. [Viewing camera moves close to the object in `inspect()`](https://github.com/mozilla/hubs/blob/master/src/systems/camera-system.js#L286-L292)
3. In the next [renderer's `render()`](https://github.com/MozillaReality/three.js/blob/hubs/master/src/renderers/WebGLRenderer.js#L1033) and [in the beginning of the next tick()](https://github.com/mozilla/hubs/blob/master/src/systems/camera-system.js#L354) and , [the audio listener's world matrix is updated as the listener is under the viewing camera and the panner position is updated so](https://github.com/MozillaReality/three.js/blob/hubs/master/src/audio/AudioListener.js#L116-L137)
4. [In the tick() audio listener is reparented with avatar pov](https://github.com/mozilla/hubs/blob/master/src/systems/camera-system.js#L502-L513)
5. In the next renderer's `render()`, audio listener's world matrix is updated as the listener is under the avatar pov and the panner position is updated so

The panner position is close to the object just for one frame (3 in the above list) and this causes an audio noise.

**How to resolve**

Insert the code reparenting the audio listener in `inspect()`. With this change, the audio world matrix and panner position are calculated as it's under the avatar pov in the 3 in the above list.

**Should we insert the code in `uninspect()`, too?**

We shouldn't. If we do, 

1. The audio listener is reparented with the viewing camera in `uninspect()`
2. The viewing camera is still close to the object and the audio listener world matrix and the panner position is updated
3. The viewing camera move back close to the avatar

and it causes an audio noise.

**Future ideal change**

The state management in camera system seems complex. We may need to refactor at some point. But the change can be big so I'd like to suggest merging this PR so far as quick patch and then thinking of refactoring later.

### CODE REVIEW

File: src/systems/camera-system.js [hunk 1]
```diff
@@ -290,6 +290,7 @@ export class CameraSystem {
       this.pivot,
       distanceMod || 1
     );
+    this.ensureListenerIsParentedCorrectly(scene);
```
Comment (johnshaughnessy) [inline src/systems/camera-system.js:293]: In this case `AudioListener.updateMatrixWorld` will not be called in `moveRigSoCameraLooksAtPivot`, so we could do it in either order. To me though, it seems more correct to call `ensureListenerIsParentedCorrectly` _before_ `moveRigSoCameraLooksAtPivot`. 

In its current order, we move the camera (the `AudioListener`'s parent) close to the object, then reparent the `AudioListener` so that it remains close to the avatar. It seems like an accident that `AudioListener.updateMatrixWorld` wasn't called in `moveRigSoCameraLooksAtPivot`. If it were, then we would still be experiencing the blip.

For this reason, I recommend calling `ensureListenerIsParentedCorrectly` _before_ `moveRigSoCameraLooksAtPivot` and also _before_ `orbit` (in `tick`)

**Review by johnshaughnessy — APPROVED** [review]
Thanks for this fix!

File: src/systems/camera-system.js (hunk 1 above)
Comment (takahirox) [reply src/systems/camera-system.js:293]: OK, your suggestion sounds safer. I'll update.

Comment (takahirox) [reply src/systems/camera-system.js]: Done
