### PR TITLE
Fix gltf loader animations and using PBR materials on mobile for camera/loading cube

### LINKED ISSUE #809: Animated model gets clipped
If you paste this model, it disappears when you walk too close to it:

https://sketchfab.com/models/f6b9171340504bc9a244ea993d524632

### PR DESCRIPTION
**Pull request by robertlong**
- Fixes animations in models with duplicate node names.
- Camera and loading cube now use the gltf-model-plus `loadModel` function and `cloneObject3D` which will correctly apply materials and clone animations/BVH data.
- Depends on https://github.com/MozillaReality/three.js/pull/39 and https://github.com/mozilla/Spoke/pull/713
- Fixes https://github.com/mozilla/Spoke/issues/446
- Fixes https://github.com/mozilla/Spoke/issues/625
- Fixes #809

### CODE REVIEW

File: src/components/gltf-model-plus.js [hunk 1]
```diff
@@ -376,9 +338,38 @@ export async function loadGLTF(src, contentType, preferredTechnique, onProgress,
     Object.keys(fileMap).forEach(URL.revokeObjectURL);
   }
 
+  gltf.scene.animations = gltf.animations;
+
   return gltf;
 }
 
+export async function loadModel(src, contentType = null, useCache = false, jsonPreprocessor = null) {
```
Comment (netpro2k) [inline src/components/gltf-model-plus.js]: I assume this just got shuffled around. Be extra careful when merging to make sure nothing gets lost.

File: src/components/loop-animation.js [hunk 2]
```diff
@@ -7,7 +7,9 @@ import { findAncestorWithComponent } from "../utils/scene-graph";
 AFRAME.registerComponent("loop-animation", {
   schema: {
     paused: { type: "boolean", default: false },
-    clip: { type: "string" }
+    /* DEPRECATED: Use animation instead since animation names are not unique */
```
Comment (netpro2k) [inline src/components/loop-animation.js]:
```suggestion
    /* DEPRECATED: Use activeClipIndex instead since animation names are not unique */
```

File: src/components/media-loader.js [hunk 3]
```diff
@@ -10,19 +10,22 @@ import {
...
 
 const SHAPE = require("aframe-physics-system/src/constants").SHAPE;
 
-const gltfLoader = new THREE.GLTFLoader();
 let loadingObjectEnvMap;
 let loadingObject;
-gltfLoader.load(loadingObjectSrc, gltf => {
-  loadingObject = gltf;
+
+window.addEventListener("DOMContentLoaded", () => {
```
Comment (netpro2k) [inline src/components/media-loader.js]: use the `waitForDOMContentLoaded` helper in async-utils

File: src/components/gltf-model-plus.js [hunk 4]
```diff
@@ -376,9 +338,38 @@ export async function loadGLTF(src, contentType, preferredTechnique, onProgress,
     Object.keys(fileMap).forEach(URL.revokeObjectURL);
   }
 
+  gltf.scene.animations = gltf.animations;
```
[the remark this answers is not in the document]
Comment (robertlong) [reply src/components/gltf-model-plus.js]: `cloneObject3D` looks for the animations array on the Object3D so we need that to happen before we clone the gltf scene.

File: src/components/gltf-model-plus.js [hunk 5]
```diff
@@ -221,10 +177,16 @@ const inflateEntities = function(indexToEntityMap, node, templates, isRoot, mode
...
   // Set the name of the `THREE.Group` to match the name of the node,
+  // so that templates can be attached to the correct AFrame entity.
+  el.object3D.name = node.name;
+
+  // Set the uuid of the `THREE.Group` to match the uuid of the node,
   // so that `THREE.PropertyBinding` will find (and later animate)
   // the group. See `PropertyBinding.findNode`:
   // https://github.com/mrdoob/three.js/blob/dev/src/animation/PropertyBinding.js#L211
-  el.object3D.name = node.name;
+  el.object3D.uuid = node.uuid;
```
[the remark this answers is not in the document]
Comment (robertlong) [reply src/components/gltf-model-plus.js]: Yep 😬
